version: '3.8'

services:
  cardano_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  cardano_app:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - cardano_db
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
